<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE etiqueta [
<!ELEMENT etiqueta (nombre, calle, ciudad, pais, codigo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
]>
<etiqueta>
  <nombre>Pepe Pérez</nombre>
  <calle>C/ Sin nombre, 17</calle>
  <ciudad>Albal</ciudad>
  <pais>España</pais>
  <codigo>46470</codigo>
</etiqueta>
